version: '2'

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 3

  app:
    build: .
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env.db
    depends_on:
      db:
        condition: service_healthy
