version: '2'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 3

  app:
    build: .
    restart: always
    container_name: app
    env_file:
      - .env.test
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pytest"
