version: '2'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 3

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
    env_file:
      - .env.db
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env.db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
