version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 30s
      retries: 3

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    container_name: app
    env_file:
      - .env.test
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "pytest"
